test: add normalizeintensity test
juancarlosfarah/apero pull request #45
Opened 2022-02-13 01:52 UTC by hannatolle

closes #44

2022-04-12 09:28 UTC, juancarlosfarah requested changes
Just a minor change in the default test!

2022-04-19 16:49 UTC, hannatolle commented on test/operations/NormalizeIntensityTest.m
> +   'meanIntensity', 1000, ...
hmm yes that's correct. But why are we passing 'verbose' then? I feel like I was passing in default values in many default tests. Now I realize that it doesn't make much sense...

2022-04-20 09:37 UTC, juancarlosfarah approved these changes
👍

2022-04-20 09:38 UTC, juancarlosfarah commented on test/operations/NormalizeIntensityTest.m
> +   'meanIntensity', 1000, ...
Indeed. We shouldn't need to pass the values that are defined by default.

2022-04-20 09:38 UTC, merged